In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("mostRequiredSkill.csv")

In [4]:
data.head()

Career Personality Type                Skill
0  Software Developer             INTP  Analytical thinking
1    Business Analyst             ENTJ   Strategic planning
2     Project Manager             ESTJ      Time management
3   Quality Assurance             ISTJ  Attention to detail
4      UI/UX Engineer             ENFP           Creativity

In [5]:
data.shape

(68, 3)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Career            68 non-null     object
 1   Personality Type  68 non-null     object
 2   Skill             68 non-null     object
dtypes: object(3)
memory usage: 1.7+ KB


In [7]:
# Find unique values of Personality types
data['Personality Type'].unique()

array(['INTP', 'ENTJ', 'ESTJ', 'ISTJ', 'ENFP', 'INTJ', 'ISTP', 'ENTP',
       'INFP'], dtype=object)

In [8]:
# Find unique values of Skills
data['Skill'].unique()

array(['Analytical thinking', 'Strategic planning', 'Time management',
       'Attention to detail', 'Creativity', 'Statistical analysis',
       'Problem solving', 'Innovation', 'Technical knowledge',
       'Writing skills'], dtype=object)

In [9]:
# Find unique values of CS career
data['Career'].unique()

array(['Software Developer', 'Business Analyst', 'Project Manager',
       'Quality Assurance', 'UI/UX Engineer', 'Data Scientist',
       'Cybersecurity Analyst', 'Cloud Architect', 'Network Engineer',
       'Technical Writer'], dtype=object)

In [6]:
# Convert text values to numeric values
career_convertion_result = data['Career']
from sklearn.preprocessing import LabelEncoder
obj1 = LabelEncoder()
result1 = obj1.fit_transform(career_convertion_result)

In [7]:
result1

array([7, 0, 5, 6, 9, 3, 2, 1, 4, 8, 7, 0, 5, 6, 9, 3, 2, 1, 4, 8, 7, 0,
       5, 6, 9, 3, 2, 1, 4, 8, 7, 0, 5, 6, 9, 3, 2, 1, 4, 8, 7, 0, 5, 6,
       9, 3, 2, 1, 4, 8, 7, 0, 5, 6, 9, 3, 2, 1, 4, 8, 7, 0, 5, 6, 9, 3,
       2, 1])

In [8]:
# Add new column and save the text to numeric conversion result
data['Career_result'] = result1
data

Career Personality Type                 Skill  \
0      Software Developer             INTP   Analytical thinking   
1        Business Analyst             ENTJ    Strategic planning   
2         Project Manager             ESTJ       Time management   
3       Quality Assurance             ISTJ   Attention to detail   
4          UI/UX Engineer             ENFP            Creativity   
..                    ...              ...                   ...   
63      Quality Assurance             ISTJ   Attention to detail   
64         UI/UX Engineer             ENFP            Creativity   
65         Data Scientist             INTJ  Statistical analysis   
66  Cybersecurity Analyst             ISTP       Problem solving   
67        Cloud Architect             ENTP            Innovation   

    Career_result  
0               7  
1               0  
2               5  
3               6  
4               9  
..            ...  
63              6  
64              9  
65              3  
66              2  
67              1  

[68 rows x 4 columns]

In [9]:
# Convert text values to numeric values
personality_convertion_result = data['Personality Type']
from sklearn.preprocessing import LabelEncoder
obj2 = LabelEncoder()
result2 = obj2.fit_transform(personality_convertion_result)

In [10]:
result2

array([6, 1, 3, 7, 0, 5, 8, 2, 7, 4, 6, 1, 3, 7, 0, 5, 8, 2, 7, 4, 6, 1,
       3, 7, 0, 5, 8, 2, 7, 4, 6, 1, 3, 7, 0, 5, 8, 2, 7, 4, 6, 1, 3, 7,
       0, 5, 8, 2, 7, 4, 6, 1, 3, 7, 0, 5, 8, 2, 7, 4, 6, 1, 3, 7, 0, 5,
       8, 2])

In [11]:
data['Personality_result'] = result2
data

Career Personality Type                 Skill  \
0      Software Developer             INTP   Analytical thinking   
1        Business Analyst             ENTJ    Strategic planning   
2         Project Manager             ESTJ       Time management   
3       Quality Assurance             ISTJ   Attention to detail   
4          UI/UX Engineer             ENFP            Creativity   
..                    ...              ...                   ...   
63      Quality Assurance             ISTJ   Attention to detail   
64         UI/UX Engineer             ENFP            Creativity   
65         Data Scientist             INTJ  Statistical analysis   
66  Cybersecurity Analyst             ISTP       Problem solving   
67        Cloud Architect             ENTP            Innovation   

    Career_result  Personality_result  
0               7                   6  
1               0                   1  
2               5                   3  
3               6                   7  
4               9                   0  
..            ...                 ...  
63              6                   7  
64              9                   0  
65              3                   5  
66              2                   8  
67              1                   2  

[68 rows x 5 columns]

In [12]:
# Convert text values to numeric values
skill_convertion_result = data['Skill']
from sklearn.preprocessing import LabelEncoder
obj3 = LabelEncoder()
result3 = obj3.fit_transform(skill_convertion_result)

In [13]:
data['Skill_result'] = result3
data

Career Personality Type                 Skill  \
0      Software Developer             INTP   Analytical thinking   
1        Business Analyst             ENTJ    Strategic planning   
2         Project Manager             ESTJ       Time management   
3       Quality Assurance             ISTJ   Attention to detail   
4          UI/UX Engineer             ENFP            Creativity   
..                    ...              ...                   ...   
63      Quality Assurance             ISTJ   Attention to detail   
64         UI/UX Engineer             ENFP            Creativity   
65         Data Scientist             INTJ  Statistical analysis   
66  Cybersecurity Analyst             ISTP       Problem solving   
67        Cloud Architect             ENTP            Innovation   

    Career_result  Personality_result  Skill_result  
0               7                   6             0  
1               0                   1             6  
2               5                   3             8  
3               6                   7             1  
4               9                   0             2  
..            ...                 ...           ...  
63              6                   7             1  
64              9                   0             2  
65              3                   5             5  
66              2                   8             4  
67              1                   2             3  

[68 rows x 6 columns]

In [14]:
x = data[['Personality_result','Skill_result']]

In [15]:
y = data['Career_result']

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [17]:
x_train.shape

(54, 2)

In [18]:
x_test.shape

(14, 2)

# Train the model - Decision Tree

In [19]:
# Implementing the decision tree model & Training the model
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train.values, y_train.values)

DecisionTreeClassifier()

In [20]:
pred = model.predict(x_test.values)

In [21]:
y_test

47    1
27    1
54    9
22    5
10    7
48    4
29    8
15    3
21    0
1     0
20    7
62    5
9     8
34    9
Name: Career_result, dtype: int32

In [22]:
# Test the accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

1.0

In [23]:
# Reversing lable encoder
# Get the text values of test set of y
y_inverted = obj1.inverse_transform(y_test)
y_inverted

array(['Cloud Architect', 'Cloud Architect', 'UI/UX Engineer',
       'Project Manager', 'Software Developer', 'Network Engineer',
       'Technical Writer', 'Data Scientist', 'Business Analyst',
       'Business Analyst', 'Software Developer', 'Project Manager',
       'Technical Writer', 'UI/UX Engineer'], dtype=object)

In [24]:
# Get the real text values of predicted
pred_inverted = obj1.inverse_transform(pred)
pred_inverted

array(['Cloud Architect', 'Cloud Architect', 'UI/UX Engineer',
       'Project Manager', 'Software Developer', 'Network Engineer',
       'Technical Writer', 'Data Scientist', 'Business Analyst',
       'Business Analyst', 'Software Developer', 'Project Manager',
       'Technical Writer', 'UI/UX Engineer'], dtype=object)

In [25]:
#More information about the y_test values vs predicted data values
y_test_pred_result = pd.DataFrame(data=[y_inverted, pred_inverted], index = ['y_test','pred'])
y_test_pred_result.transpose()

y_test                pred
0      Cloud Architect     Cloud Architect
1      Cloud Architect     Cloud Architect
2       UI/UX Engineer      UI/UX Engineer
3      Project Manager     Project Manager
4   Software Developer  Software Developer
5     Network Engineer    Network Engineer
6     Technical Writer    Technical Writer
7       Data Scientist      Data Scientist
8     Business Analyst    Business Analyst
9     Business Analyst    Business Analyst
10  Software Developer  Software Developer
11     Project Manager     Project Manager
12    Technical Writer    Technical Writer
13      UI/UX Engineer      UI/UX Engineer

# Give new values to x and predict y

In [26]:
# Giving new values and assign them to a variable
input_values = [[6, 0]]
pred_result = model.predict(input_values)
pred_result

array([7])

In [27]:
# Invert the result because of numerical format
pred_result_inverted = obj1.inverse_transform(pred_result)
pred_result_inverted

array(['Software Developer'], dtype=object)